/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinPoker
import java.util.*

data class Card(val suit: String, val rank : String){
    override fun toString() = "${rank}${suit}"

    fun hasSameSuit(other : Card) = suit == other.suit

    fun hasSameRank(other : Card) = rank == other.rank
}

data class Cards(val cards: List<Card>){
    fun isPair() : Boolean = TODO("未実装")
}