/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinPoker

data class Card(val suit: Suit, val rank : Rank){
    override fun toString() = "${rank.value}${suit.value}"

    fun hasSameSuit(other : Card) = suit == other.suit

    fun hasSameRank(other : Card) = rank == other.rank
}

data class Cards(val cards: List<Card>){
    fun getHand() : String = when  {
        cards[0].rank == cards[1].rank -> "Pair"
        cards[0].suit == cards[1].suit -> "Flush"
        else -> "HighCard"
    }
}

enum class Rank(val value : Int){
    ACE(1),
    TWO(2),
    THREE(3),
    FOUR(4),
    FIVE(5),
    SIX(6),
    SEVEN(7),
    EIGHT(8),
    NINE(9),
    TEN(10),
    JACK(11),
    QUEEN(12),
    KING(13)
}
enum class Suit(val value : String){
    CLUB("♣"),
    SPADE("♠"),
    HEART("♥"),
    DIA("◆")
}




