/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinPoker

import org.assertj.core.api.Assertions.*
import org.junit.Before
import org.junit.Test

class AppTest {
    @Test fun testAppHasAGreeting() {
        val app = App()
        app.let{
            assertThat(it.greeting).isEqualTo("Hello world")
        }
        
    }
}
